//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuzzyRiskNet.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Examples {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Examples() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FuzzyRiskNet.Models.Examples", typeof(Examples).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;$id&quot;:&quot;1&quot;,&quot;Criteria&quot;:[],&quot;GPNConfigurations&quot;:[{&quot;$id&quot;:&quot;2&quot;,&quot;Project&quot;:{&quot;$ref&quot;:&quot;1&quot;},&quot;Name&quot;:&quot;Configuration 1&quot;},{&quot;$id&quot;:&quot;3&quot;,&quot;Project&quot;:{&quot;$ref&quot;:&quot;1&quot;},&quot;Name&quot;:&quot;Configuration 2&quot;}],&quot;Nodes&quot;:[{&quot;$id&quot;:&quot;4&quot;,&quot;Dependencies&quot;:[{&quot;$id&quot;:&quot;5&quot;,&quot;From&quot;:{&quot;$ref&quot;:&quot;4&quot;},&quot;To&quot;:{&quot;$id&quot;:&quot;6&quot;,&quot;Dependencies&quot;:[{&quot;$id&quot;:&quot;7&quot;,&quot;From&quot;:{&quot;$ref&quot;:&quot;6&quot;},&quot;To&quot;:{&quot;$ref&quot;:&quot;4&quot;},&quot;GPNConfiguration&quot;:null,&quot;Rate&quot;:{&quot;$id&quot;:&quot;8&quot;,&quot;A&quot;:0.704,&quot;B&quot;:0.759,&quot;C&quot;:0.815,&quot;IsZero&quot;:false}},{&quot;$id&quot;:&quot;9&quot;,&quot;From&quot;:{&quot;$ref&quot;:&quot;6&quot;},&quot;To&quot;:{&quot;$ref&quot;:&quot;4&quot;},&quot;GPNConfigura....
        /// </summary>
        internal static string Example1 {
            get {
                return ResourceManager.GetString("Example1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;$id&quot;:&quot;1&quot;,&quot;Criteria&quot;:[],&quot;GPNConfigurations&quot;:[],&quot;Nodes&quot;:[{&quot;$id&quot;:&quot;2&quot;,&quot;Dependencies&quot;:[{&quot;$id&quot;:&quot;3&quot;,&quot;From&quot;:{&quot;$ref&quot;:&quot;2&quot;},&quot;To&quot;:{&quot;$id&quot;:&quot;4&quot;,&quot;Dependencies&quot;:[{&quot;$id&quot;:&quot;5&quot;,&quot;From&quot;:{&quot;$ref&quot;:&quot;4&quot;},&quot;To&quot;:{&quot;$ref&quot;:&quot;2&quot;},&quot;GPNConfiguration&quot;:null,&quot;Rate&quot;:{&quot;$id&quot;:&quot;6&quot;,&quot;A&quot;:0.3936,&quot;B&quot;:0.3993,&quot;C&quot;:0.58,&quot;IsZero&quot;:false}},{&quot;$id&quot;:&quot;7&quot;,&quot;From&quot;:{&quot;$ref&quot;:&quot;4&quot;},&quot;To&quot;:{&quot;$id&quot;:&quot;8&quot;,&quot;Dependencies&quot;:[{&quot;$id&quot;:&quot;9&quot;,&quot;From&quot;:{&quot;$ref&quot;:&quot;8&quot;},&quot;To&quot;:{&quot;$ref&quot;:&quot;2&quot;},&quot;GPNConfiguration&quot;:null,&quot;Rate&quot;:{&quot;$id&quot;:&quot;10&quot;,&quot;A&quot;:0.1321,&quot;B&quot;:0.133....
        /// </summary>
        internal static string Example2 {
            get {
                return ResourceManager.GetString("Example2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;$id&quot;:&quot;1&quot;,&quot;Criteria&quot;:[],&quot;GPNConfigurations&quot;:[{&quot;$id&quot;:&quot;2&quot;,&quot;Project&quot;:{&quot;$ref&quot;:&quot;1&quot;},&quot;Name&quot;:&quot;Configuration 2&quot;},{&quot;$id&quot;:&quot;3&quot;,&quot;Project&quot;:{&quot;$ref&quot;:&quot;1&quot;},&quot;Name&quot;:&quot;Configuration 3&quot;},{&quot;$id&quot;:&quot;4&quot;,&quot;Project&quot;:{&quot;$ref&quot;:&quot;1&quot;},&quot;Name&quot;:&quot;Configuration 1&quot;}],&quot;Nodes&quot;:[{&quot;$id&quot;:&quot;5&quot;,&quot;Dependencies&quot;:[],&quot;Project&quot;:{&quot;$ref&quot;:&quot;1&quot;},&quot;Region&quot;:{&quot;$id&quot;:&quot;6&quot;,&quot;Name&quot;:&quot;Europe&quot;,&quot;ParentID&quot;:null,&quot;RegionLevel&quot;:null},&quot;Role&quot;:null,&quot;Name&quot;:&quot;Base Constituents&quot;,&quot;FullName&quot;:&quot;Base Constituents (Europe)&quot;,&quot;LocationX&quot;:0,&quot;LocationY&quot;:0,&quot;DefaultPurturbation&quot;:{&quot;$id&quot;:&quot;7&quot;,&quot;A&quot;:0.0,&quot;B&quot;....
        /// </summary>
        internal static string Example3 {
            get {
                return ResourceManager.GetString("Example3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;$id&quot;:&quot;1&quot;,&quot;Criteria&quot;:[{&quot;$id&quot;:&quot;2&quot;,&quot;Indicator&quot;:null,&quot;Parent&quot;:null,&quot;Values&quot;:[],&quot;Weights&quot;:[{&quot;$id&quot;:&quot;3&quot;,&quot;Criteria&quot;:{&quot;$ref&quot;:&quot;2&quot;},&quot;GPNConfiguration&quot;:{&quot;$id&quot;:&quot;4&quot;,&quot;Project&quot;:{&quot;$ref&quot;:&quot;1&quot;},&quot;Name&quot;:&quot;Internal Bike Supplier Only&quot;},&quot;Node&quot;:{&quot;$id&quot;:&quot;5&quot;,&quot;Dependencies&quot;:[],&quot;Project&quot;:{&quot;$ref&quot;:&quot;1&quot;},&quot;Region&quot;:{&quot;$id&quot;:&quot;6&quot;,&quot;Name&quot;:&quot;Germany&quot;,&quot;Parent&quot;:null,&quot;RegionLevel&quot;:null},&quot;Role&quot;:{&quot;$ref&quot;:&quot;2&quot;},&quot;Name&quot;:&quot;Product Development&quot;,&quot;FullName&quot;:&quot;Product Development (Germany)&quot;,&quot;LocationX&quot;:1,&quot;LocationY&quot;:0,&quot;DefaultPurturbation&quot;:{&quot;$id&quot;:&quot;7&quot;,&quot;A&quot;:0.0,&quot;B&quot;:0.0 [rest of....
        /// </summary>
        internal static string Example4 {
            get {
                return ResourceManager.GetString("Example4", resourceCulture);
            }
        }
    }
}
