//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuzzyRiskNet.Libraries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FuzzyRiskNet.Utility.Forms.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Items.
        /// </summary>
        public static string AllItems {
            get {
                return ResourceManager.GetString("AllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string DeleteConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has been saved successfully..
        /// </summary>
        public static string EditSuccessfulMessage {
            get {
                return ResourceManager.GetString("EditSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string GridFirst {
            get {
                return ResourceManager.GetString("GridFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string GridLast {
            get {
                return ResourceManager.GetString("GridLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string GridNext {
            get {
                return ResourceManager.GetString("GridNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewing {0} to {1} from {2}.
        /// </summary>
        public static string GridPageMessage {
            get {
                return ResourceManager.GetString("GridPageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string GridPrev {
            get {
                return ResourceManager.GetString("GridPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date entered for {0} is in incorrect format..
        /// </summary>
        public static string IncorrectDateMessage {
            get {
                return ResourceManager.GetString("IncorrectDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string Inserting {
            get {
                return ResourceManager.GetString("Inserting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string InsertTitle {
            get {
                return ResourceManager.GetString("InsertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value entered for {0} is not numerical..
        /// </summary>
        public static string NonNumericalMessage {
            get {
                return ResourceManager.GetString("NonNumericalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records exist..
        /// </summary>
        public static string NoRecordsMessage {
            get {
                return ResourceManager.GetString("NoRecordsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been deleted..
        /// </summary>
        public static string RecordDeleted {
            get {
                return ResourceManager.GetString("RecordDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been added..
        /// </summary>
        public static string RecordInserted {
            get {
                return ResourceManager.GetString("RecordInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been updated..
        /// </summary>
        public static string RecordUpdated {
            get {
                return ResourceManager.GetString("RecordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string RequiredMessage {
            get {
                return ResourceManager.GetString("RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to list.
        /// </summary>
        public static string ReturnToListTitle {
            get {
                return ResourceManager.GetString("ReturnToListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        public static string Root {
            get {
                return ResourceManager.GetString("Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string RowNo {
            get {
                return ResourceManager.GetString("RowNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveTitle {
            get {
                return ResourceManager.GetString("SaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for {0} should be in the past while it is in future..
        /// </summary>
        public static string ShouldBeInThePastMessage {
            get {
                return ResourceManager.GetString("ShouldBeInThePastMessage", resourceCulture);
            }
        }
    }
}
